name: 'Deploy to Pantheon'
description: 'Deploy codebase to Pantheon'
inputs:
  PANTHEON_PRIVATE_KEY:
    description: "The private RSA key you will save in the Github Secrets"
    required: true
  PANTHEON_TERMINUS_MACHINE_TOKEN:
    description: "The private RSA key you will save in the Github Secrets"
    required: true
  PANTHEONENV:
    description: "Default env to be deployed,"
    required: false
    default: 'dev'
author: 'colin-simpli'
runs:
  using: 'composite'
  steps:
    - id: deploy
      env:
        COMMITMSG: ${{ github.event.head_commit.message }}
        COMMITID: ${{ github.sha }}
      run: |
        export GH_COMMITID=${COMMITID}
        export GH_COMMITMSG=${COMMITMSG}
        ${{ github.action_path }}/scripts/github/setup-terminus.sh
        printf "[\e[0;34mNOTICE\e[0m] Pantheon Deploy script COMPLETE!!!.\n"
      working-directory: .
      shell: bash
branding:
  icon: 'cloud-lightning'
  color: 'yellow'